# Generated by Django 4.2.11 on 2024-06-18 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 6, 18, 11, 48, 34, 79963, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
