# Generated by Django 4.2.11 on 2024-06-18 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_date_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default_image.jpg", upload_to="photos/"),
        ),
        migrations.AddField(
            model_name="post",
            name="quotes",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
