# Generated by Django 3.2.12 on 2024-06-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_featured_article_living'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='bedroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='outdoor',
            field=models.BooleanField(default=False),
        ),
    ]
